// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core.Extensions;
using WebApi;

namespace Microsoft.Extensions.Azure
{
    /// <summary> Extension methods to add <see cref="WebApiClient"/> to client builder. </summary>
    public static partial class WebApiClientBuilderExtensions
    {
        /// <summary> Registers a <see cref="WebApiClient"/> instance. </summary>
        /// <param name="builder"> The builder to register with. </param>
        /// <param name="endpoint"> server parameter. </param>
        public static IAzureClientBuilder<WebApiClient, WebApiClientOptions> AddWebApiClient<TBuilder>(this TBuilder builder, Uri endpoint)
        where TBuilder : IAzureClientFactoryBuilder
        {
            return builder.RegisterClientFactory<WebApiClient, WebApiClientOptions>((options) => new WebApiClient(endpoint, options));
        }

        /// <summary> Registers a <see cref="WebApiClient"/> instance. </summary>
        /// <param name="builder"> The builder to register with. </param>
        /// <param name="configuration"> The configuration values. </param>
        public static IAzureClientBuilder<WebApiClient, WebApiClientOptions> AddWebApiClient<TBuilder, TConfiguration>(this TBuilder builder, TConfiguration configuration)
        where TBuilder : IAzureClientFactoryBuilderWithConfiguration<TConfiguration>
        {
            return builder.RegisterClientFactory<WebApiClient, WebApiClientOptions>(configuration);
        }
    }
}
